version: "3.9" 

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: sistemademensajes-rabbitmq-1
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:15
    container_name: sistemademensajes-postgres-1
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather_pass
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  producer:
    build: ./producer
    container_name: sistemademensajes-producer-1
    volumes:
      - ./producer:/app
    depends_on:
      - rabbitmq

  consumer:
    build: ./consumer
    container_name: sistemademensajes-consumer-1
    depends_on:
      - rabbitmq
      - postgres

volumes:
  rabbitmq_data:
  postgres_data:

