version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: sistemademensajes-rabbitmq-1
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_prometheus true"

  postgres:
    image: postgres:15
    container_name: sistemademensajes-postgres-1
    environment:
      POSTGRES_USER: weather
      POSTGRES_PASSWORD: weather_pass
      POSTGRES_DB: weatherdb
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

  producer:
    build: ./producer
    container_name: sistemademensajes-producer-1
    volumes:
      - ./producer:/app
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq

  consumer:
    build: ./consumer
    container_name: sistemademensajes-consumer-1
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - postgres

  prometheus:
    image: prom/prometheus
    container_name: sistemademensajes-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - producer
      - consumer

  grafana:
    image: grafana/grafana
    container_name: sistemademensajes-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  rabbitmq_data:
  postgres_data:
  grafana_data:
