global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "producer"
    static_configs:
      - targets: ["producer:8001"]

  - job_name: "consumer"
    static_configs:
      - targets: ["consumer:8000"]

  - job_name: "rabbitmq"
    metrics_path: /metrics
    static_configs:
      - targets: ["rabbitmq:15692"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
